CREATE TABLE IF NOT EXISTS TB_CATEGORY (
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME CHARACTER VARYING(50) NOT NULL,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UNIQUE(NAME)
);